### ISSUE TITLE
Document how to expose ingress on VIP address managed by Talos Linux

### ISSUE THREAD

**Issue by kvaps** [aenix-io/cozystack-website#17]
This might be really useful infromation for small setups

eg:
```yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: cozystack
  namespace: cozy-metallb
spec:
  addresses:
  - 192.168.100.10/32
  autoAssign: true
  avoidBuggyIPs: false
```

without announce
